package com.huntercodexs.cryptography.toolkit;

import org.junit.jupiter.api.Test;

import static com.huntercodexs.cryptography.toolkit.CryptographyToolkit.decryptAesCbc256DynamicFULL_AUTO_GENERATED;
import static com.huntercodexs.cryptography.toolkit.CryptographyToolkit.encryptAesCbc256DynamicFULL_AUTO_GENERATED;
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;

class CryptographyToolkitDynamicFULLAUTOGENERATEDTests {

    @Test
    public void encryptAES256CBC_PARAMETER_FULL_AUTO_GENERATE_Test() {
        /* ! DO NOT CHANGE THE INFORMATION HERE ! */
        String result = encryptAesCbc256DynamicFULL_AUTO_GENERATED("This is a secret message, please don't break it !");
        assertEquals(171, result.length());
        assertTrue(result.contains("/x0t0x00001p#"));

        String resultDecrypt = decryptAesCbc256DynamicFULL_AUTO_GENERATED(result);
        assertEquals("This is a secret message, please don't break it !", resultDecrypt);
    }

    @Test
    public void decryptAES256CBC_PARAMTER_FULL_AUTO_GENERATE_Test() {
        /* ! DO NOT CHANGE THE INFORMATION HERE ! */
        String result = decryptAesCbc256DynamicFULL_AUTO_GENERATED(
                "NDFFNjQ2RUQ$MEU0QjRFNTQ$XD+LSM87ZC5aR2wly25mVYzlsLnOe90aH375GjUTmgOjB4MDAxMDE6OjB4MTEwMTA6/x0t0x00001p#REY0QjQ0NTM$MzA1RTIxNTE$6Nhqt/JrdfgMDO3l1d4pLMs6iO3qk6Xe5tQS5yY+/5cH");
        assertEquals("This is a secret message, please don't break it !", result);
    }

}
